name: KiBot

# Controls when the action will run.
on:
  push:
    paths:
      - "board/output/pcbs/*.kicad_sch"
      - "board/output/pcbs/*.kicad_pcb"
      - "board/*.kibot.yaml"
      - ".github/workflows/kibot.yml"
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - "board/output/pcbs/*.kicad_sch"
      - "board/output/pcbs/*.kicad_pcb"
      - "board/*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  KIBOT:
    runs-on: ubuntu-slim
    steps:
      - run: | 
          sudo apt update
          sudo apt install -y kicad
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3 
      - run: | # use https://nickcoutsos.github.io/keymap-layout-tools/ to generate info.json 
          touch board/output/pcbs/sessile.kicad_sch
          echo '(kicad_sch (version 20230121))' > board/output/pcbs/sessile.kicad_sch

          uvx kibot \
              -c board/sessile.kibot.yaml \
              -d board/output/pcbs \
              -b board/output/pcbs/sessile.kicad_pcb \
              -e board/output/pcbs/sessile.kicad_sch \
              ZIP_ASSEMBLY
      - uses: actions/upload-artifact@v4
        with:
          name: pcb
          path: board/output/pcbs/jlcpcb.zip

  release:
    runs-on: ubuntu-slim
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: KIBOT
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pcb
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "jlcpcb.zip"