name: KiBot

# Controls when the action will run.
on:
  push:
    paths:
      - "board/output/pcbs/*.kicad_sch"
      - "board/output/pcbs/*.kicad_pcb"
      - "board/*.kibot.yaml"
      - ".github/workflows/kibot.yml"
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - "board/output/pcbs/*.kicad_sch"
      - "board/output/pcbs/*.kicad_pcb"
      - "board/*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  KIBOT:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: astral-sh/setup-uv@v3 
        # with:
        #   config: board/sessile.kibot.yaml
        #   dir: board/output/pcbs
        # #   variant: board
        #   board: board/output/pcbs/sessile.kicad_pcb
        #   schema: board/output/pcbs/sessile.kicad_sch
        #   skip: erc
        #   targets: ZIP_ASSEMBLY
      - run: | # use https://nickcoutsos.github.io/keymap-layout-tools/ to generate info.json 
          wget https://set-soft.github.io/debian/kibot.sources
          sudo cp kibot.sources /etc/apt/sources.list.d/
          sudo apt update
          sudo apt install -y kibot

          kibot \
              -c board/sessile.kibot.yaml \
              -d board/output/pcbs \
              -b board/output/pcbs/sessile.kicad_pcb \
              -s board/output/pcbs/sessile.kicad_sch \
              --skip erc \
              --targets ZIP_ASSEMBLY
      - uses: actions/upload-artifact@v4
        with:
          name: pcb
          path: board/output/pcbs/jlcpcb.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: KIBOT
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pcb
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "jlcpcb.zip"