name: KiBot

# Controls when the action will run.
on:
  push:
    paths:
      - "board/output/pcbs/*.kicad_sch"
      - "board/output/pcbs/*.kicad_pcb"
      - "board/*.kibot.yaml"
      - ".github/workflows/kibot.yml"
    tags:
      - "v*.*.*"
  pull_request:
    paths:
      - "board/output/pcbs/*.kicad_sch"
      - "board/output/pcbs/*.kicad_pcb"
      - "board/*.kibot.yaml"
      - ".github/workflows/kibot.yml"
  repository_dispatch:
    types: [run_gha]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  DRC:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk9
        with:
          config: board/sessile.kibot.yaml
          dir: board/output/pcbs
          board: board/output/pcbs/sessile.kicad_pcb
          skip: erc
          targets: __NONE__

  BOARD:
    runs-on: ubuntu-latest
    needs: [DRC]
    steps:
      - uses: actions/checkout@v4
      - uses: INTI-CMNB/KiBot@v2_dk9
        with:
          config: board/sessile.kibot.yaml
          dir: board/output/pcbs
          board: board/output/pcbs/sessile.kicad_pcb
          variant: board
          skip: erc,drc
          targets: ZIP_ASSEMBLY
      - uses: actions/upload-artifact@v4
        with:
          name: pcb
          path: board/output/pcbs/jlcpcb.zip

  release:
    runs-on: ubuntu-latest
    if: startsWith(github.ref, 'refs/tags/')
    permissions:
      contents: write
    needs: BOARD
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: pcb
      - name: Release
        uses: softprops/action-gh-release@v2
        with:
          files: "jlcpcb.zip"